import Header from "@/app/_components/Header";
import "@/app/_styles/globals.css";

import { Josefin_Sans } from "next/font/google";
import ProgressWrap from "./_components/ProgressWrap";
import Analytics from "./_components/Analytics";

const josefin = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${josefin.className} bg-white flex flex-col min-h-screen`}
      >
        <Analytics />
        <Header />
        <main className="flex-1 py-12 grid w-full">
          <div className="container mx-auto">{children}</div>
        </main>
        <footer className="w-full py-4 text-white bg-primary-purple text-center">
          Copyright © 2024 The Win Team
        </footer>
        <ProgressWrap />
      </body>
    </html>
  );
}
